# Generated by Django 2.2.5 on 2019-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
